# Stub vcpkg toolchain — use system packages (Boost, etc.)
if(NOT DEFINED VCPKG_TARGET_TRIPLET)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|AMD64")
        set(VCPKG_TARGET_TRIPLET "x64-linux")
    else()
        set(VCPKG_TARGET_TRIPLET "arm64-linux")
    endif()
endif()
set(VCPKG_MANIFEST_MODE OFF)
message(STATUS "Using stub vcpkg toolchain (system packages)")