//THIS IS EITHER A TEMPLATE OR AN AUTOGENERATED FILE
//IF THE FILENAME IS version_generated.h DON'T EDIT IT - EDIT version_template.h INSTEAD!

const char *GIT_HASH = "#GITHASH#";
const char *BUILD_DATE = __DATE__;

#ifdef _DEBUG
const char *BUILD_CONFIG="debug";
#else
const char *BUILD_CONFIG="";
#endif

//do not change anything on this line except what's in the quotes
//python parses this file to pull out the version number
const char *SDNA_VERSION = "4.1.1";
