name: Build sdna_plus

on:
  push:
    branches: [ Cross_platform ]
  pull_request:
    branches: [ Cross_platform ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container_image:
          - ubuntu:26.04
          - ubuntu:24.04
          - ubuntu:22.04
          - ubuntu:20.04
          - debian:bookworm
          - debian:bullseye
          - debian:trixie

    
    container:
      image: ${{ matrix.container_image }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
        
    - name: "Configure apy to use Kitware's repos (for CMake 3.29+)"
      run: |
        apt update
        apt install -y ca-certificates gpg wget
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | tee /etc/apt/sources.list.d/kitware.list
        apt update
    
    - name: Install dependencies
      run: |
        apt install -y cmake make g++ libboost-dev python3 git
        
    - name: Clone sdna_plus repository
      run: |
        git clone --depth=1 --branch=build-linux-openmp https://github.com/Robinlovelace/sdna_plus/
    
    - name: Build sdna_plus
      continue-on-error: true # Even when the build is successful, the interactive script hangs at a "read" command
      run: |
        cd sdna_plus
        bash build_linux.sh

    - name: Smoke test
      working-directory: sdna_plus
      run: |
        export sdnadll=$(pwd)/output/Release/x64/sdna_vs2008.so
        cd sDNA/sdna_vs2008/tests
        python3 prepare_test_new.py
    
    - name: Upload build artifacts (optional)
      uses: actions/upload-artifact@v4
      with:
        name: sdna_plus-build
        path: sdna_plus/
      if: always()  # Upload even if build fails for debugging




      
